
lci_repowering(extension_long=True, extension_short=False, substitution=False, repowering=False,
                   park_name_i="Cabril I", park_power_i=16.2, number_of_turbines_i=9,
                   park_location_i='PT',
                   park_coordinates_i=(40.98,-8.045),
                   manufacturer_i='Enercon',
                   rotor_diameter_i=66,
                   turbine_power_i=1.8, hub_height_i=84.35, commissioning_year_i=2002,
                   recycled_share_steel_i=None,
                   lifetime_i=22,
                   electricity_mix_steel_i='Europe',
                   generator_type_i='dd_eesg',
                   lifetime_extension=None, number_of_turbines_extension: int = None,
                   cf_extension: float = None, time_adjusted_cf_extension: float = 0.009,
                   lifetime_substitution: int = 25, number_of_turbines_substitution= 9,
                   cf_substitution = 0.208, time_adjusted_cf_substitution= 0.009,
                   recycled_share_steel_extension = 0.6,
                   park_power_repowering: float = None,
                   number_of_turbines_repowering: int = None,
                   manufacturer_repowering: str = None,
                   rotor_diameter_repowering: int = None,
                   turbine_power_repowering: float = None,
                   hub_height_repowering: float = None,
                   generator_type_repowering: Optional[Literal['dd_eesg', 'dd_pmsg', 'gb_pmsg', 'gb_dfig']] = 'dd_eesg',
                   electricity_mix_steel_repowering: Optional[Literal['Norway', 'Europe', 'Poland']] = 'Europe',
                   lifetime_repowering: int = 25,
                   recycled_share_steel_repowering: float = None,
                   cf_repowering: float = 0.293,
                   attrition_rate_repowering: float = 0.009,
                   land_use_permanent_intensity_repowering: int = 3000,
                   land_cover_type_repowering: str = 'industrial',
                   eol_scenario_repowering: int = 1,
                   eol: bool = True, transportation: bool = True, use_and_maintenance: bool = True,
                   installation: bool = True
                   )

lci_repowering(extension_long: bool, extension_short: bool, substitution: bool, repowering: bool,
                   park_name_i: str, park_power_i: float, number_of_turbines_i: int,
                   park_location_i: str,
                   park_coordinates_i: tuple,
                   manufacturer_i: Literal['Vestas', 'Siemens Gamesa', 'Nordex', 'Enercon', 'LM Wind'],
                   rotor_diameter_i: float,
                   turbine_power_i: float, hub_height_i: float, commissioning_year_i: int,
                   recycled_share_steel_i: float = None,
                   lifetime_i: int = 20,
                   electricity_mix_steel_i: Optional[Literal['Norway', 'Europe', 'Poland']] = None,
                   generator_type_i: Literal['dd_eesg', 'dd_pmsg', 'gb_pmsg', 'gb_dfig'] = 'gb_dfig',
                   lifetime_extension: int = None, number_of_turbines_extension: int = None,
                   cf_extension: float = None, time_adjusted_cf_extension: float = 0.009,
                   lifetime_substitution: int = None, number_of_turbines_substitution: int = None,
                   cf_substitution: float = None, time_adjusted_cf_substitution: float = 0.009,
                   recycled_share_steel_extension: float = None,
                   park_power_repowering: float = None,
                   number_of_turbines_repowering: int = None,
                   manufacturer_repowering: str = None,
                   rotor_diameter_repowering: int = None,
                   turbine_power_repowering: float = None,
                   hub_height_repowering: float = None,
                   generator_type_repowering: Optional[Literal['dd_eesg', 'dd_pmsg', 'gb_pmsg', 'gb_dfig']] = 'gb_dfig',
                   electricity_mix_steel_repowering: Optional[Literal['Norway', 'Europe', 'Poland']] = 'Europe',
                   lifetime_repowering: int = 25,
                   recycled_share_steel_repowering: float = None,
                   cf_repowering: float = 0.24,
                   attrition_rate_repowering: float = 0.009,
                   land_use_permanent_intensity_repowering: int = 3000,
                   land_cover_type_repowering: str = 'industrial',
                   eol_scenario_repowering: int = 1,
                   eol: bool = True, transportation: bool = True, use_and_maintenance: bool = True,
                   installation: bool = True
                   )

lci_excel_output(park_name: park_name + scenario, extension, repowering_short or extension_long, substitution, park_power_repowering, file_path)